# database
ClientID = "ad6c335e71344854a7a6a39927a59f2d"
ClientSecret = "rpFY1oJLeDLOajj3KvIgYzdUyNUwJ486"
ServerHost = "localhost"
ServerPort = "8400"
PgHost = "127.0.0.1"
PgPort = "5432"
PgUser = "admin"
PgPass = "22357890"
PgBase = "telegram"
